version: '3.8'

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8500
    volumes:
      - .:/code
      - sqlite_data:/code/db.sqlite3
    ports:
      - "8500:8500"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5175:5175"
    depends_on:
      - backend

volumes:
  sqlite_data:
