# Generated by Django 5.0.6 on 2024-06-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('apply_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('details', models.TextField()),
                ('selected_categories', models.JSONField()),
                ('current_participants', models.IntegerField(default=1)),
            ],
        ),
    ]
