# Generated by Django 5.0.6 on 2024-06-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makemeeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_name',
            field=models.CharField(max_length=25),
        ),
    ]
